spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/cargodb"
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 5000
  flyway:
    schemas: public
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

springdoc:
  paths-to-match: /**
  packages-to-scan: com.github.cargoclean.infrastructure.adapter.web.handling

logging:
  level:
    com:
      github:
        cargoclean: debug
    org:
      springframework:
        jdbc: debug
        data:
          jdbc: debug
        security: debug

cargo:
  location-cache:
    name: "locationCache"
    init-capacity: 10
    maximum-size: 100
    ttl: 1h
  slow-load:
    enabled: true
    delay-millis: 150
